# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwords_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(232, 319)
        Form.frame = QtWidgets.QFrame(Form)
        Form.frame.setGeometry(QtCore.QRect(10, 10, 215, 301))
        Form.frame.setStyleSheet("background-color: white;\n"
"border-radius:8px;\n"
"border-bottom-left-radius: 6px;\n"
"border-bottom-right-radius: 6px;\n"
"")
        Form.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Form.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        Form.frame.setObjectName("frame")
        Form.label_5 = QtWidgets.QLabel(Form.frame)
        Form.label_5.setGeometry(QtCore.QRect(0, 9, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        Form.label_5.setFont(font)
        Form.label_5.setAlignment(QtCore.Qt.AlignCenter)
        Form.label_5.setObjectName("label_5")
        Form.label_6 = QtWidgets.QLabel(Form.frame)
        Form.label_6.setGeometry(QtCore.QRect(0, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        Form.label_6.setFont(font)
        Form.label_6.setStyleSheet("background-color: transparent;")
        Form.label_6.setAlignment(QtCore.Qt.AlignCenter)
        Form.label_6.setObjectName("label_6")
        Form.frame_7 = QtWidgets.QFrame(Form.frame)
        Form.frame_7.setGeometry(QtCore.QRect(0, 60, 215, 1))
        Form.frame_7.setStyleSheet("background-color:rgb(214, 214, 214); border-radius: none;")
        Form.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Form.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        Form.frame_7.setObjectName("frame_7")
        Form.btn_exit = QtWidgets.QPushButton(Form.frame)
        Form.btn_exit.setGeometry(QtCore.QRect(170, 16, 28, 28))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        Form.btn_exit.setFont(font)
        Form.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Form.btn_exit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 242, 242);\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 242, 242);\n"
"}")
        Form.btn_exit.setText("")
        Form.btn_exit.setObjectName("btn_exit")
        Form.softtitle_move_frame = QtWidgets.QFrame(Form.frame)
        Form.softtitle_move_frame.setGeometry(QtCore.QRect(0, 0, 215, 61))
        Form.softtitle_move_frame.setStyleSheet("background-color: transparent;")
        Form.softtitle_move_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Form.softtitle_move_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        Form.softtitle_move_frame.setObjectName("softtitle_move_frame")
        Form.listWidget = QtWidgets.QListWidget(Form.frame)
        Form.listWidget.setGeometry(QtCore.QRect(7, 69, 201, 192))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(8)
        Form.listWidget.setFont(font)
        Form.listWidget.setStyleSheet("    background-color: rgb(242, 242, 242);\n"
"    border-radius: 6px;\n"
"color: grey;")
        Form.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        Form.listWidget.setObjectName("listWidget")
        Form.lineEdit = QtWidgets.QLineEdit(Form.frame)
        Form.lineEdit.setGeometry(QtCore.QRect(10, 270, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        Form.lineEdit.setFont(font)
        Form.lineEdit.setStyleSheet("border: 1px solid grey; color: grey; border-radius:none;")
        Form.lineEdit.setInputMask("")
        Form.lineEdit.setText("")
        Form.lineEdit.setObjectName("lineEdit")
        Form.btn_add = QtWidgets.QPushButton(Form.frame)
        Form.btn_add.setGeometry(QtCore.QRect(150, 270, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        Form.btn_add.setFont(font)
        Form.btn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Form.btn_add.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 242, 242);\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 211, 211);\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 242, 242);\n"
"}")
        Form.btn_add.setObjectName("btn_add")
        Form.label_5.raise_()
        Form.label_6.raise_()
        Form.frame_7.raise_()
        Form.softtitle_move_frame.raise_()
        Form.btn_exit.raise_()
        Form.listWidget.raise_()
        Form.lineEdit.raise_()
        Form.btn_add.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.label_5.setText(_translate("Form", "PASSWORDS"))
        Form.label_6.setText(_translate("Form", "[t.me/quicksellbot]"))
        Form.lineEdit.setPlaceholderText(_translate("Form", "password"))
        Form.btn_add.setText(_translate("Form", "Add"))
