# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searcher_new_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(273, 225)
        MainWindow.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.centralwidget.setObjectName("centralwidget")
        MainWindow.frame = QtWidgets.QFrame(MainWindow.centralwidget)
        MainWindow.frame.setGeometry(QtCore.QRect(0, 0, 271, 221))
        MainWindow.frame.setStyleSheet("background-color: white;\n"
"border-radius:8px;\n"
"border-bottom-left-radius: 6px;\n"
"border-bottom-right-radius: 6px;\n"
"")
        MainWindow.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MainWindow.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        MainWindow.frame.setObjectName("frame")
        MainWindow.label_5 = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.label_5.setGeometry(QtCore.QRect(47, 8, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.label_5.setFont(font)
        MainWindow.label_5.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.label_5.setObjectName("label_5")
        MainWindow.label_6 = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.label_6.setGeometry(QtCore.QRect(50, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.label_6.setFont(font)
        MainWindow.label_6.setStyleSheet("background-color: transparent;")
        MainWindow.label_6.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.label_6.setObjectName("label_6")
        MainWindow.frame_7 = QtWidgets.QFrame(MainWindow.frame)
        MainWindow.frame_7.setGeometry(QtCore.QRect(0, 60, 271, 1))
        MainWindow.frame_7.setStyleSheet("background-color:rgb(214, 214, 214); border-radius: none;")
        MainWindow.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MainWindow.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        MainWindow.frame_7.setObjectName("frame_7")
        MainWindow.lineEdit = QtWidgets.QLineEdit(MainWindow.frame)
        MainWindow.lineEdit.setGeometry(QtCore.QRect(40, 70, 141, 21))
        MainWindow.lineEdit.setStyleSheet("border: 1px solid grey; color: grey; border-radius:none;")
        MainWindow.lineEdit.setInputMask("")
        MainWindow.lineEdit.setText("")
        MainWindow.lineEdit.setObjectName("lineEdit")
        MainWindow.label_7 = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.label_7.setGeometry(QtCore.QRect(10, 72, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.label_7.setFont(font)
        MainWindow.label_7.setStyleSheet("color:grey;background-color: transparent;")
        MainWindow.label_7.setObjectName("label_7")
        MainWindow.btn_choose = QtWidgets.QPushButton(MainWindow.frame)
        MainWindow.btn_choose.setGeometry(QtCore.QRect(190, 70, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        MainWindow.btn_choose.setFont(font)
        MainWindow.btn_choose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.btn_choose.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 242, 242);\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 211, 211);\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 242, 242);\n"
"}")
        MainWindow.btn_choose.setObjectName("btn_choose")
        MainWindow.frame_8 = QtWidgets.QFrame(MainWindow.frame)
        MainWindow.frame_8.setGeometry(QtCore.QRect(0, 100, 271, 1))
        MainWindow.frame_8.setStyleSheet("background-color:rgb(214, 214, 214); border-radius: none;")
        MainWindow.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MainWindow.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        MainWindow.frame_8.setObjectName("frame_8")
        MainWindow.change_steamCookies = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.change_steamCookies.setGeometry(QtCore.QRect(180, 122, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.change_steamCookies.setFont(font)
        MainWindow.change_steamCookies.setStyleSheet("color:black; border: none;")
        MainWindow.change_steamCookies.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        MainWindow.change_steamCookies.setObjectName("change_steamCookies")
        MainWindow.label_12 = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.label_12.setGeometry(QtCore.QRect(10, 122, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.label_12.setFont(font)
        MainWindow.label_12.setStyleSheet("color:grey; border: none;")
        MainWindow.label_12.setObjectName("label_12")
        MainWindow.btn_search = QtWidgets.QPushButton(MainWindow.frame)
        MainWindow.btn_search.setGeometry(QtCore.QRect(10, 160, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        MainWindow.btn_search.setFont(font)
        MainWindow.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.btn_search.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 242, 242);\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 211, 211);\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 242, 242);\n"
"}")
        MainWindow.btn_search.setObjectName("btn_search")
        MainWindow.btn_exit = QtWidgets.QPushButton(MainWindow.frame)
        MainWindow.btn_exit.setGeometry(QtCore.QRect(225, 16, 28, 28))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        MainWindow.btn_exit.setFont(font)
        MainWindow.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.btn_exit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 242, 242);\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 242, 242);\n"
"}")
        MainWindow.btn_exit.setText("")
        MainWindow.btn_exit.setObjectName("btn_exit")
        MainWindow.softtitle_move_frame = QtWidgets.QFrame(MainWindow.frame)
        MainWindow.softtitle_move_frame.setGeometry(QtCore.QRect(0, 0, 271, 61))
        MainWindow.softtitle_move_frame.setStyleSheet("background-color: transparent;")
        MainWindow.softtitle_move_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MainWindow.softtitle_move_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        MainWindow.softtitle_move_frame.setObjectName("softtitle_move_frame")
        MainWindow.progressBar = QtWidgets.QProgressBar(MainWindow.frame)
        MainWindow.progressBar.setGeometry(QtCore.QRect(6, 200, 258, 15))
        MainWindow.progressBar.setStyleSheet("QProgressBar {\n"
"  border-radius: 10px;\n"
"  border-top-left-radius: 0px;  \n"
"  border-top-right-radius: 0px;\n"
"  color: transparent;\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"  background-color: black;  \n"
"  color: transparent;\n"
"width: 10px;                   \n"
"margin: 0.5px;\n"
"}")
        MainWindow.progressBar.setProperty("value", 50)
        MainWindow.progressBar.setTextVisible(False)
        MainWindow.progressBar.setObjectName("progressBar")
        MainWindow.checkBox_archives = QtWidgets.QCheckBox(MainWindow.frame)
        MainWindow.checkBox_archives.setGeometry(QtCore.QRect(190, 105, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.checkBox_archives.setFont(font)
        MainWindow.checkBox_archives.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.checkBox_archives.setStyleSheet("\n"
"QCheckBox {\n"
"    color: grey;\n"
"}\n"
"QCheckBox::indicator {\n"
"    background: rgb(242, 242, 242);\n"
"    color: white;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background : grey;\n"
"    border: 3px solid  rgb(242, 242, 242);\n"
"}")
        MainWindow.checkBox_archives.setObjectName("checkBox_archives")
        MainWindow.btn_managePasswords = QtWidgets.QPushButton(MainWindow.frame)
        MainWindow.btn_managePasswords.setGeometry(QtCore.QRect(9, 105, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.btn_managePasswords.setFont(font)
        MainWindow.btn_managePasswords.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"color: grey;\n"
"}\n"
"QPushButton:hover {\n"
"    border-radius: 4px;\n"
"    color: rgb(90, 90, 90)\n"
"}\n"
"QPushButton:pressed {\n"
"color: grey;\n"
"}")
        MainWindow.btn_managePasswords.setObjectName("btn_managePasswords")
        MainWindow.label_9 = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.label_9.setGeometry(QtCore.QRect(10, 140, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.label_9.setFont(font)
        MainWindow.label_9.setStyleSheet("color:grey; border: none;")
        MainWindow.label_9.setObjectName("label_9")
        MainWindow.change_totalaccs = QtWidgets.QLabel(MainWindow.frame)
        MainWindow.change_totalaccs.setGeometry(QtCore.QRect(180, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.change_totalaccs.setFont(font)
        MainWindow.change_totalaccs.setStyleSheet("color:black; border: none;")
        MainWindow.change_totalaccs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        MainWindow.change_totalaccs.setObjectName("change_totalaccs")
        MainWindow.label_5.raise_()
        MainWindow.label_6.raise_()
        MainWindow.frame_7.raise_()
        MainWindow.label_7.raise_()
        MainWindow.btn_choose.raise_()
        MainWindow.lineEdit.raise_()
        MainWindow.frame_8.raise_()
        MainWindow.change_steamCookies.raise_()
        MainWindow.label_12.raise_()
        MainWindow.btn_search.raise_()
        MainWindow.softtitle_move_frame.raise_()
        MainWindow.btn_exit.raise_()
        MainWindow.progressBar.raise_()
        MainWindow.checkBox_archives.raise_()
        MainWindow.btn_managePasswords.raise_()
        MainWindow.label_9.raise_()
        MainWindow.change_totalaccs.raise_()
        MainWindow.setCentralWidget(MainWindow.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.label_5.setText(_translate("MainWindow", "STEAM SORTER"))
        MainWindow.label_6.setText(_translate("MainWindow", "[t.me/quicksellbot]"))
        MainWindow.label_7.setText(_translate("MainWindow", "Path"))
        MainWindow.btn_choose.setText(_translate("MainWindow", "Choose"))
        MainWindow.change_steamCookies.setText(_translate("MainWindow", "0"))
        MainWindow.label_12.setText(_translate("MainWindow", "Found steam cookies"))
        MainWindow.btn_search.setText(_translate("MainWindow", "Search"))
        MainWindow.checkBox_archives.setText(_translate("MainWindow", "Archives"))
        MainWindow.btn_managePasswords.setText(_translate("MainWindow", "Manage archive passwords"))
        MainWindow.label_9.setText(_translate("MainWindow", "Total accs (no dubles)"))
        MainWindow.change_totalaccs.setText(_translate("MainWindow", "0"))
